Project/core/views.py
from flask import Flask, Response, flash, render_template, request, Blueprint, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
import time
import requests
import lxml.html as lh
import pandas as pd
import re
from datetime import date
from datetime import datetime
import sqlite3 as sql
from sqlite3 import Error
from Project import db
from werkzeug.utils import secure_filename
import numpy
from PIL import Image as im
from base64 import b64encode
from sqlalchemy.sql import exists
import random


from Project.core.forms import LoginForm, RegistrationForm, UploadForm
from Project.models import User, Items, RentedItems
from Project import razorpay_client

core=Blueprint('core',__name__)

price=0
product_id=0
sdate=0
edate=0

@core.route('/', methods=['GET','POST'])
def index():
    return render_template("home.html")

# @core.route('/login', methods=['GET','POST'])
# def login():
#     form1=LoginForm()
#     if form1.submit1.data and form1.validate():
#         next=url_for('core.index')
#         user=User.query.filter_by(email=form1.email.data).first()
#         if user is not None and user.check_password(form1.password.data):
#             login_user(user)
#             next=request.args.get('next')

#             if next==None or not next[0] == '/':
#                 next=url_for('core.index')
#         else:
#             flash('Wrong login credentials')
#         return redirect(next)
#     return render_template("login.html",form=form1)

# @core.route('/signup', methods=['GET','POST'])
# def signup():
#     form2=RegistrationForm()

#     if form2.submit2.data and form2.validate():
#         if User.query.filter_by(email=form2.email.data).first() == None:
#             user=User(fname=form2.fname.data , lname=form2.lname.data, email=form2.email.data, password=form2.password.data, phone=form2.phone.data, address=form2.address.data)
#             db.session.add(user)
#             db.session.commit()
#         else:
#             flash('An account with this email already exists')
#         return redirect(url_for('core.index'))
    
#     return render_template("signup.html", form=form2)

@core.route('/uploadform', methods=['GET','POST'])
@login_required
def uploadForm():
    return render_template("upload.html")

@core.route('/upload', methods=['POST'])
def upload():
    nm=request.form['item']
    # nm='Computer Chair'
    file1=request.files['file1']
    file2=request.files['file2']
    file3=request.files['file3']
    pr=request.form['price']
    cat=request.form['dropdown']

    item=Items(item_name=nm, image1=file1.read(), image2=file2.read(), image3=file3.read(), price=pr, category=cat,supplier_id=current_user.id)
    db.session.add(item)
    db.session.commit()
    
    return redirect(url_for('core.index'))

@core.route('/available', methods=['GET','POST'])
@login_required
def available():
    # products=Items.query.paginate(per_page=100)
    # products = Items.query.filter(Items.supplier_id != current_user.id).paginate(per_page=100)
    products = Items.query.filter(Items.supplier_id != current_user.id).filter(~exists().where(Items.id == RentedItems.item_id)).paginate(per_page=100)
    for product in products.items:
        product.image1=b64encode(product.image1).decode("utf-8")
    length=len(products.items)
    return render_template('available.html', products=products, length=length)

@core.route('/rent', methods=['GET', 'POST'])
def rentItem():
    product_id=request.form['pid']
    # print(product_id)
    item=Items.query.filter_by(id = product_id).one()
    item.image1=b64encode(item.image1).decode("utf-8")
    item.image2=b64encode(item.image2).decode("utf-8")
    item.image3=b64encode(item.image3).decode("utf-8")

    supplier=User.query.filter_by(id=item.supplier_id).one()
    return render_template('rentitem.html', product=item, supplier=supplier)

@core.route('/checkout', methods=['GET','POST'])
def  checkout():
    global price, product_id, sdate, edate
    product_id=request.form['pid']
    supplier_id=request.form['sid']
    start_date=request.form['start']
    end_date=request.form['end']

    product=Items.query.filter_by(id = product_id).one()
    supplier=User.query.filter_by(id=product.supplier_id).one()

    
    delta=datetime.strptime(end_date, '%Y-%m-%d')-datetime.strptime(start_date, '%Y-%m-%d')
    delta=delta.days
    # print(type(end_date))

    price=int(delta*product.price*100)
    sdate=datetime.strptime(start_date, '%Y-%m-%d').date()
    edate=datetime.strptime(end_date, '%Y-%m-%d').date()
    product_id=product.id

    return render_template('checkout.html', product=product, supplier=supplier, price=price/100, days=delta, start=start_date, end=end_date, order_id=random.randint(1,100))

@core.route('/charge', methods=['POST'])
def charge():
    global price, sdate, edate, product_id
    amount = price
    # print(amount)
    payment_id = request.form['razorpay_payment_id']
    razorpay_client.payment.capture(payment_id, amount)
    # print(payment_id)
    # return json.dumps(razorpay_client.payment.fetch(payment_id))
    ritem=RentedItems(item_id=product_id, start_date=sdate, end_date=edate, tenant_id=current_user.id, amount=price/100,payment_id=payment_id)
    db.session.add(ritem)
    db.session.commit()
    return redirect(url_for('core.index'))

@core.route('/dashboard', methods=['GET','POST'])
@login_required
def dashboard():
    # items_rented = RentedItems.query.join(Items, Items.id == RentedItems.item_id).join(User, User.id == Items.supplier_id).filter(RentedItems.tenant_id == current_user.id).all()
    items_rented = db.session.query(RentedItems, Items, User).join(Items, Items.id == RentedItems.item_id).join(User, User.id == Items.supplier_id).filter(RentedItems.tenant_id == current_user.id).all()
    # items_lent=Items.query.join(RentedItems, Items.id == RentedItems.item_id).join(User, User.id == Items.supplier_id).filter(Items.supplier_id == current_user.id).paginate(per_page=100)
    items_lent = db.session.query(Items, RentedItems, User).join(RentedItems, Items.id == RentedItems.item_id).join(User, User.id == RentedItems.tenant_id).filter(Items.supplier_id == current_user.id).all()
    # ri=len(items_rented.items)
    li=len(items_lent)
    ri=len(items_rented)
    for i in items_rented:
        i.RentedItems.start_date=i.RentedItems.start_date.date()
        i.RentedItems.end_date=i.RentedItems.end_date.date()
    
    for i in items_lent:
        i.RentedItems.start_date=i.RentedItems.start_date.date()
        i.RentedItems.end_date=i.RentedItems.end_date.date()

    return render_template("dashboard.html",rented=items_rented, lent=items_lent, ri=ri, li=li)

Project/users/views.py
from flask import Flask, flash, render_template, request, Blueprint, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
import time
import requests
import lxml.html as lh
import pandas as pd
import re
from datetime import date
from Project.core.forms import LoginForm, RegistrationForm
from Project.models import User
from Project import db

users=Blueprint('users',__name__)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

@users.route('/login', methods=['GET','POST'])
def login():
    form1=LoginForm()
    if form1.submit1.data and form1.validate():
        next=url_for('core.index')
        user=User.query.filter_by(email=form1.email.data).first()
        if user is not None and user.check_password(form1.password.data):
            login_user(user)
            next=request.args.get('next')

            if next==None or not next[0] == '/':
                next=url_for('core.index')
        else:
            flash('Wrong login credentials')
        return redirect(next)
    return render_template("login.html",form=form1)

@users.route('/signup', methods=['GET','POST'])
def signup():
    form2=RegistrationForm()

    if form2.submit2.data and form2.validate():
        if User.query.filter_by(email=form2.email.data).first() == None:
            user=User(fname=form2.fname.data , lname=form2.lname.data, email=form2.email.data, password=form2.password.data, phone=form2.phone.data, address=form2.address.data)
            db.session.add(user)
            db.session.commit()
        else:
            flash('An account with this email already exists')
        return redirect(url_for('core.index'))
    
    return render_template("signup.html", form=form2)

Project/templates/available.html
<!doctype html>
<html lang="en">
  <head>
  	<title>NearRent</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="../static/available.css">
    <style>
        body {
          background-image: url('../static/background.jpeg');
          background-repeat: no-repeat;
          background-attachment: fixed;
          background-size: cover;
        }
    </style>  

	</head>
	<body>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
              <a class="navbar-brand" href="#" style="color: #000080;font-weight: bolder;font-family: 'Roboto Slab',serif; font-size:xx-large;">NearRent</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('core.index')}}" style="color: rgb(33,37,41);"><b>HOME</b></a>
                  </li>
                  {% if current_user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('core.uploadForm')}}" style="color: rgb(33,37,41);"><b>LEND</b></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('core.available')}}" style="color: rgb(33,37,41);"><b>RENT</b></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('core.dashboard')}}" style="color: rgb(33,37,41);"><b>DASHBOARD</b></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('users.logout')}}" style="color: rgb(33,37,41);"><b>LOGOUT</b></a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.login')}}" style="color: rgb(33,37,41);"><b>LOGIN</b></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.signup')}}" style="color: rgb(33,37,41);"><b>SIGN UP</b></a>
                  </li>
                  {% endif %}
                  <!-- <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                  </li> -->
                </ul>
              </div>
            </div>
        </nav>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-4">
					<h2 class="heading-section"><b>ITEMS AVAILABLE FOR RENT</b></h2>
				</div>
			</div>
      {% if length!=0 %}
			<div class="row">
				<div class="col-md-12">
					<!-- <h3 class="h5 mb-4 text-center">Table Accordion</h3> -->
					<div class="table-wrap">
						<table class="table">
						  <thead class="thead-primary">
						    <tr>
						    	<th><p style="font-size:large;font-weight:800">Product Image</p></th>
						    	<th><p style="font-size:large;font-weight:800">Product Name</p></th>
                  <th><p style="font-size:large;font-weight:800">Product Category</p></th>
						      <th><p style="font-size:large;font-weight:800">Price per day</p></th>
                  <th>&nbsp;&nbsp;</th>
						    </tr>
						  </thead>
						  <tbody>
                {% for product in products.items %}
						    <tr class="alert" role="alert">
						    	
						    	<td>
						    		<div class="img" style="background-image: url(data:image/png;base64,{{product.image1}});"></div>
						    	</td>
						      <td>
						      	<p style="font-size:medium;font-weight:700">{{product.item_name}}</p>
						      </td>
						      <td><p style="font-size:medium;font-weight:700">{{product.category}}</p></td>
						      
				          <td><p style="font-size:medium;font-weight:700">₹{{product.price}}</p></td>
                  <td>
                    <form method="post" action="{{url_for('core.rentItem')}}">
                      <input type="text" id="fname" name="pid" value={{product.id}} style="display:none">
                      <button type="submit">RENT</button>
                    </form>
                  </td>
						      
						    </tr>
                {% endfor %}
						  </tbody>
						</table>
					</div>
				</div>
			</div>
      {% else %}
      <h3 style="text-align:center;">No items available for rent</h3>
      {% endif %}
		</div>
	</section>

    <script src="../static/jquery.min.js"></script>
    <script src="../static/popper.js"></script>
    <script src="../static/bootstrap.min.js"></script>
    <script src="../static/main.js"></script>

	</body>
</html>

Project/templates/checkout.html
{% extends "header.html" %}
{% block content %}
<br><br>
<div style="margin-left: 10%;margin-right:10%">

    <h2 style="text-align: center;"><b>BILL SUMMARY ({{start}} - {{end}})</b></h2>
    <br><br>
    <table style="margin-left:auto;margin-right: auto;padding: 10px;border: 1px solid black;border-collapse: collapse;">
        <tr>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">PRODUCT NAME &nbsp;&nbsp;&nbsp;</p></th>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">CATEGORY &nbsp;&nbsp;&nbsp;</p></th>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">PRICE/DAY &nbsp;&nbsp;&nbsp;</p></th>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">DURATION (DAYS) &nbsp;&nbsp;&nbsp;</p></th>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">BILL AMOUNT &nbsp;&nbsp;&nbsp;</p></th>
        </tr>
        <tr>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">{{product.item_name}}</td>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">{{product.category}}</td>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">{{product.price}}</td>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">{{days}}</td>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">₹{{price}}</td>
        </tr>
    </table>
    <br><br>
    <h2 style="text-align:center;"><b>SUPPLIER INFORMATION</b></h2>
    <table style="margin-left:auto;margin-right: auto;padding: 10px;border: 1px solid black;border-collapse: collapse;">
        <tr>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">NAME &nbsp;&nbsp;&nbsp;</p></th>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">EMAIL &nbsp;&nbsp;&nbsp;</p></th>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">WHATSAPP NUMBER &nbsp;&nbsp;&nbsp;</p></th>
            <th style="padding: 10px;border: 1px solid black;border-collapse: collapse;"><p style="font-size:120%;font-weight:bold">ADDRESS &nbsp;&nbsp;&nbsp;</p></th>
        </tr>
        <tr>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">{{supplier.first_name}} {{supplier.last_name}}</td>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">{{supplier.email}}</td>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">{{supplier.phone}}</td>
            <td style="padding: 10px;border: 1px solid black;border-collapse: collapse;">{{supplier.address}}</td>
        </tr>
    </table>
    <br><br><br>

    <center>
        <form action="{{url_for('core.charge')}}" method="POST" style="margin: 0 auto;">
            <script
            src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="rzp_test_PFJOfZjOFHbKk5"
            data-amount={{price*100}}
            data-name="NearRent"
            data-description="Purchase Description"
            data-image="vk.jpg"
            data-netbanking="true"
            data-description="Tron Legacy"
            data-prefill.name={{current_user.first_name}}
            data-prefill.email={{current_user.email}}
            data-prefill.contact={{current_user.phone}}
            data-notes.shopping_order_id={{order_id}}>
            </script>
            <input type="hidden" name="shopping_order_id" value="21">
        </form>

    </center>
    

</div>




{% endblock %}

Project/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NearRent</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../static/main.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="color: #000080;font-weight: bolder;font-family: 'Roboto Slab',serif; font-size:xx-large;">NearRent</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('core.index')}}" style="color: rgb(33,37,41);"><b>HOME</b></a>
              </li>
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('core.uploadForm')}}" style="color: rgb(33,37,41);"><b>LEND</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('core.available')}}" style="color: rgb(33,37,41);"><b>RENT</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('core.dashboard')}}" style="color: rgb(33,37,41);"><b>DASHBOARD</b></a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('users.logout')}}" style="color: rgb(33,37,41);"><b>LOGOUT</b></a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('users.login')}}" style="color: rgb(33,37,41);"><b>LOGIN</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('users.signup')}}" style="color: rgb(33,37,41);"><b>SIGN UP</b></a>
              </li>
              {% endif %}
              <!-- <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li> -->
            </ul>
          </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>
</html>

Project/templates/home.html
{% extends "header.html" %}
{% block content %}

    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    
      <!-- Carousel start -->
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner" style="justify-content: center;">
        <div class="carousel-item active">
          <img src="../static/slide1.jpg" class="center-block w-100 car-image" alt="..." style="height: 650px; margin: auto; text-align: center;display: block;">
          <div class="carousel-caption d-none d-md-block">
            <!-- <h5>Register on NearRent</h5>
            <p>Sign up on NearRent to become a member.</p> -->
            <h3>BUY AND RENT COMMODITIES</h3>
          </div>
        </div>
        <div class="carousel-item">
          <img src="../static/slide2.jpg" class="d-block w-100" alt="..." style="height: 650px; margin: auto; text-align: center;display: block;">
          <div class="carousel-caption d-none d-md-block">
            <!-- <h5>Choose if you wanna lend or rent</h5>
            <p>You can upload details of the commodity you want to lend or look for renting a commodity.</p> -->
            <h3 style="color: black;">CONNECT WITH NEARBY VENDORS</h3>
          </div>
        </div>
        <div class="carousel-item">
          <img src="../static/pay.jpg" class="d-block w-100" alt="..." style="height: 650px; margin: auto; text-align: center;display: block;">
          <div class="carousel-caption d-none d-md-block">
            <!-- <h5>Churn local business</h5>
            <p>Pay for the commodities you rent or earn money by lending.</p> -->
            <h3>CHURN LOCAL BUSINESS</h3>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
      
  </div>
  <!-- Carousel end -->
  
  <!-- Intro start -->
  <div style="margin-left: 10%;margin-right: 10%;">
    {% if current_user.is_authenticated %}
      <h2 style="padding-top: 30px;">Welcome, {{current_user.first_name}}</h2>
    {% endif %}
    <h2 style="padding-top: 30px;"><b>About NearRent</b></h2>
    <p>NearRent is a peer-to-peer local 
      commodity sharing marketplace. 
      This platform allows the seller to 
      upload various goods they 
      wish to lend and the rentee to opt 
      for the items they wish to rent. This web application connects people over a local network, so that a person who wishes to rent can have an open platform to do so. 
    </p>
    <div style="margin-bottom: 10px;">
      <img src="../static/stonks.PNG" style="margin: auto; text-align: center;display: block;filter: drop-shadow(7px 7px 7px #666666);-webkit-filter: drop-shadow(7px 7px 7px #666666);">
    </div>
    <h2 style="padding-top: 30px;"><b>Lend / Rent</b></h2>
    <p>Choose to either lend commodities to our community of users on a per-day cost basis or 
      surf through the existing products available for rent and avail the benefits of our rich local rental business.
    </p>
    <div style="text-align: center;justify-content: space-between; margin-bottom: 20px;">
      <a href="{{url_for('core.uploadForm')}}"><img src="../static/lend.PNG" style="box-shadow: 7px 7px 7px #666666; width: 40%;margin-right: 50px;"></a>
      <a href="{{url_for('core.available')}}"><img src="../static/rent.PNG" style="box-shadow: 7px 7px 7px #666666; width: 40%;"></a>
    </div>
    
  </div>
{% endblock %}

Project/templates/rentitem.html
{% extends "header.html" %}
{% block content %}
<div style="margin-left: 10%;margin-right: 10%;">
    <h2><b>{{product.item_name}}</b></h2>
    <div class="card-group">
        <div class="card">
          <img class="card-img-top" src="data:image/png;base64,{{product.image1}}" alt="Card image cap" style="height: 330px">
          <div class="card-body">
            <h5 class="card-title" style="text-align:center">IMAGE 1</h5>
            <!-- <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>
        <div class="card">
          <img class="card-img-top" src="data:image/png;base64,{{product.image2}}" alt="Card image cap" style="height: 330px">
          <div class="card-body">
            <h5 class="card-title" style="text-align:center">IMAGE 2</h5>
            <!-- <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>
        <div class="card">
          <img class="card-img-top" src="data:image/png;base64,{{product.image3}}" alt="Card image cap" style="height: 330px">
          <div class="card-body">
            <h5 class="card-title" style="text-align:center">IMAGE 3</h5>
            <!-- <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>
      </div>
      <br><br>
      <h2><b>SUPPLIER INFORMATION</b></h2>
      <p style="font-size:140%;"><span style="font-weight: bold;">Name:</span> {{supplier.first_name}} {{supplier.last_name}}</p>
      <p style="font-size:140%;"><span style="font-weight: bold;">Email:</span> {{supplier.email}}</p>
      <p style="font-size:140%;"><span style="font-weight: bold;">WhatsApp Number:</span> {{supplier.phone}}</p>
      <p style="font-size:140%;"><span style="font-weight: bold;">Address:</span> {{supplier.address}}</p>

      <form method="post" action="{{url_for('core.checkout')}}">
        <input type="text" name="pid" value={{product.id}} style="display:none">
        <input type="text" name="sid" value={{supplier.id}} style="display:none">
        <label for="start">START DATE</label>
        <input type="date" id="start" name="start" value="2021-05-27">
        <label for="start">END DATE</label>
        <input type="date" id="end" name="end" value="2021-05-27">
        <button type="submit"]>MOVE TO CHECKOUT</button>
      
    </form>

</div>
   
    
{% endblock %}